name = "PeriodicHiddenMarkovModels"
uuid = "4873b48c-7fd1-4fb6-93c5-649b25bdde2e"
authors = ["David Métivier <david.metivier@inrae.fr> and contributors"]
version = "0.3.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ArgCheck = "2"
Distributions = "0.25"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
