name = "PeriodicHiddenMarkovModels"
uuid = "4873b48c-7fd1-4fb6-93c5-649b25bdde2e"
authors = ["David Métivier <david.metivier@inrae.fr> and contributors"]
version = "0.2.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
HiddenMarkovModels = "84ca31d5-effc-45e0-bfda-5a68cd981f47"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
